const express = require('express')
const app = new express
const {signUpFunc, loginFunc} = require('./controllers/maincontroller.js')
const {inboxFunc, sendFunc} = require('./controllers/messagescontroller')
const {tokencheckFuncMw} = require('./validators/tokenvalidator')
app.use(express.json())
app.post('/signup',signUpFunc)  
app.post('/login',loginFunc)
app.get('/',tokencheckFuncMw, inboxFunc)      
app.post('/send', tokencheckFuncMw,sendFunc)   
app.listen(8080, () => console.log("server is listennig on 8080 port"))     